# Generated by Django 4.2 on 2024-09-24 12:47

import database.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdgeBoxInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_box_id', models.CharField(max_length=255, unique=True)),
                ('edge_box_location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'EdgeBox Information',
                'db_table': 'edge_box_info',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=255)),
                ('status_description', models.TextField(blank=True, null=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
                ('edge_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.edgeboxinfo')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='PlantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=255, unique=True)),
                ('plant_name', models.CharField(max_length=255)),
                ('plant_location', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Plant Information',
                'db_table': 'plant_info',
                'unique_together': {('plant_name', 'plant_location')},
            },
        ),
        migrations.AddField(
            model_name='edgeboxinfo',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.plantinfo'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('media_name', models.CharField(max_length=100)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('media_file', models.FileField(upload_to=database.models.get_media_path)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_info', models.JSONField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.event')),
            ],
            options={
                'verbose_name_plural': 'Media',
                'db_table': 'media',
                'unique_together': {('event', 'media_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='edgeboxinfo',
            unique_together={('plant', 'edge_box_id')},
        ),
    ]
