# Generated by Django 4.2 on 2024-09-25 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edgeboxinfo',
            old_name='edge_box_location',
            new_name='location',
        ),
    ]
