# Generated by Django 4.2 on 2024-09-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_edge_box_location_edgeboxinfo_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('edge_box', 'event_id')},
        ),
    ]
