# Generated by Django 4.2 on 2024-09-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_event_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_name',
            field=models.CharField(max_length=255),
        ),
    ]
