# Generated by Django 4.2 on 2024-09-25 09:55

import database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_media_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_file',
            field=models.FileField(max_length=255, upload_to=database.models.get_media_path),
        ),
    ]
