# Generated by Django 4.2 on 2024-10-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_media_source_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plantinfo',
            unique_together=set(),
        ),
    ]
