# Generated by Django 4.2 on 2024-10-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_plantinfo_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
