# Generated by Django 4.2 on 2024-12-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_media_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgeboxinfo',
            name='sensor_box_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
